---
- hosts: all
  become: true

  tasks:
    - name: Install required dependencies for the Sury repository
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Get the Debian distribution codename
      ansible.builtin.shell: "lsb_release -sc"
      register: debian_codename

    - name: Add the Sury GPG key
      ansible.builtin.apt_key:
        url: https://packages.sury.org/php/apt.gpg
        state: present

    - name: Add the Sury repository
      ansible.builtin.apt_repository:
        repo: "deb https://packages.sury.org/php/ {{ debian_codename.stdout }} main"
        state: present
        update_cache: yes

    - name: Install PHP and additional modules
      apt:
        name:
          - php8.2
          - php8.2-fpm
          - php8.2-mbstring
          - php8.2-mysql
          - php8.2-curl
          - php8.2-intl
          - php8.2-gd
          - php8.2-opcache
          - php8.2-xml
          - php8.2-zip
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Clone Git repository
      git:
        repo: https://github.com/Theohrt23/Kyks_pb_repo
        dest: /var/www/kyks
        version: main

    - name: Configure Nginx
      template:
        src: ./templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/kyks
      notify: restart nginx

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/kyks
        dest: /etc/nginx/sites-enabled/kyks
        state: link
      notify: restart nginx

    - name: Install Composer
      ansible.builtin.shell: "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"
      args:
        creates: /usr/local/bin/composer

    - name: Install Symfony dependencies with Composer
      ansible.builtin.command:
        cmd: composer install --no-interaction --optimize-autoloader
        chdir: /var/www/kyks/kyks

    - name: Configure Symfony parameters
      template:
        src: ./templates/parameters.yaml.j2
        dest: /var/www/kyks/kyks/config/packages/parameters.yaml

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted