---
- hosts: all
  become: true

  tasks:
    - name: Get the Debian distribution codename
      ansible.builtin.shell: "lsb_release -sc"
      register: debian_codename

    - name: Add the Sury GPG key
      ansible.builtin.apt_key:
        url: https://packages.sury.org/php/apt.gpg
        state: present

    - name: Add the Sury repository
      ansible.builtin.apt_repository:
        repo: "deb https://packages.sury.org/php/ {{ debian_codename.stdout }}
        state: present
        update_cache: yes

    - name: Install PHP and additional modules
      apt:
        name:
          - php8.2
          - php8.2-cli
          - php8.2-fpm
          - php8.2-common
          - php8.2-json
          - php8.2-mbstring
          - php8.2-xml
          - php8.2-zip
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Clone Git repository
      git:
        repo: https://github.com/Theohrt23/Kyks_pb_repo
        dest: /var/www/kyks
        version: main

    - name: Configure Nginx
      template:
        src: ./templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/kyks
      notify: restart nginx

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/kyks
        dest: /etc/nginx/sites-enabled/kyks
        state: link
      notify: restart nginx

    - name: Install Composer dependencies
      composer:
        command: install
        working_dir: /var/www/kyks

    - name: Configure Symfony parameters
      template:
        src: ./templates/gparameters.yaml.j2
        dest: /var/www/your-project/config/packages/parameters.yaml

    - name: Clear Symfony cache
      shell: php bin/console cache:clear --env=prod

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted